### ISSUE TITLE
issue with command node wrapper.js --upgrade

### ISSUE THREAD

**Issue by Yorthopia** [FND/jslint-reporter#9]
hello.

this command warn me this error message :

TypeError: Cannot read property 'edition' of undefined
    at main (/home/christophe/dotfiles/emacs/.emacs.d/jslint-reporter/wrapper.js:69:42)
    at /home/christophe/dotfiles/emacs/.emacs.d/jslint-reporter/wrapper.js:51:4
    at IncomingMessage.<anonymous> (/home/christophe/dotfiles/emacs/.emacs.d/jslint-reporter/wrapper.js:131:4)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
 
Btw i already have jslint.js, don't know if it can help to understand.

**Comment by FND** [comment]
Thanks for reporting this - should be fixed with 448ceb6cae58010e8313939afa0dbc2508341cfb.
